public class App {
    public static void main(String[] args) throws Exception {
        //System.out.println("Hello, World!");

        //CaesarCypher a = new CaesarCypher();
        Vigenere b = new Vigenere();
        TranspositionCipher transpo = new TranspositionCipher();
        String cypher = "SERLTAREHHOEERATTOSLDOSSNAWDITLUTIHTFEARBONPLWDHDFOPGRDNANRHPSNAPHOOHLLSAARERTMONOPYNISDNOAAULDANAITLAOEEAAAIHMNHLDDGOMUOELATTTWAHIDSWIABOIMCDETHNODEERPTNIWSISSINELASAHVOONEPEETCDERFHRIOFEHEDOIEFGHTOEASGRUANLTYTHMSOTTHSPSOLLGNOFDNSSLHENIPSHCNIRGGNRNOOCERESTTOLNDYIMUONLWNYORDIOGTAOTAREHCFRRHRHILITSWSNGLIRIYAEHWLDAPDOAEDETAIKRRWISWUNAAWIOARISFDTNTEHRTEEHMOWEOSHDEOOCSIMLLHDENKNBTEAHNAAGDNGTFEWEAEHHRDEITLARHAWAJONOEDUOHIVHDUGAERFSOIENCTWEHPGTAKRTSDNEAIEGOSFRNTAHPNEDOOSBATAMLISTDDRPOAHDHWEEHBSEFSICNTEHSONETROEOETSLDAYIMRAENNIUETFPBAADEAIEBIAHCNNINHSUUTNHINOTLEEFTRDEOAPRNMGAHOLEEAHNEOADDIRNGQEIHTTTHSEPCAAMULLSISALTSHIETRRNEUEIOSAEPDAKTRDHSESKPAOMTSNCIUYOHTMATDDDDNNSHORUSDAITNCEMTEARESIIURWHGEADNHBRDUHOPDMTOSCOMRINEEELEEAWLIRNSDHUTNAHHEETUYESNTNIOSNTNIHIENSEAWDRPHTNUTCLFCIHIRETLLIRLOAISGOLDSWEHEIMJHBRGHSERITAYNNNGODMEMREDOMCNEAESSMTWEA";
        // 4 columns for SERLTAREHHOEERATTOSLDOSSNAWDITLUTIHTFEARBONPLWDHDFOPGRDNANRHPSNAPHOOHLLSAARERTMONOPYNISDNOAAULDANAITLAOEEAAAIHMNHLDDGOMUOELATTTWAHIDSWIABOIMCDETHNODEERPTNIWSISSINELASAHVOONEPEETCDERFHRIOFEHEDOIEFGHTOEASGRUANLTYTHMSOTTHSPSOLLGNOFDNSSLHENIPSHCNIRGGNRNOOCERESTTOLNDYIMUONLWNYORDIOGTAOTAREHCFRRHRHILITSWSNGLIRIYAEHWLDAPDOAEDETAIKRRWISWUNAAWIOARISFDTNTEHRTEEHMOWEOSHDEOOCSIMLLHDENKNBTEAHNAAGDNGTFEWEAEHHRDEITLARHAWAJONOEDUOHIVHDUGAERFSOIENCTWEHPGTAKRTSDNEAIEGOSFRNTAHPNEDOOSBATAMLISTDDRPOAHDHWEEHBSEFSICNTEHSONETROEOETSLDAYIMRAENNIUETFPBAADEAIEBIAHCNNINHSUUTNHINOTLEEFTRDEOAPRNMGAHOLEEAHNEOADDIRNGQEIHTTTHSEPCAAMULLSISALTSHIETRRNEUEIOSAEPDAKTRDHSESKPAOMTSNCIUYOHTMATDDDDNNSHORUSDAITNCEMTEARESIIURWHGEADNHBRDUHOPDMTOSCOMRINEEELEEAWLIRNSDHUTNAHHEETUYESNTNIOSNTNIHIENSEAWDRPHTNUTCLFCIHIRETLLIRLOAISGOLDSWEHEIMJHBRGHSERITAYNNNGODMEMREDOMCNEAESSMTWEA                 
        //System.out.println(transpo.decrypt(cypher));
        transpo.decrypt(cypher);
        //int max = 26;
        //Vigenere.everySixthChar(cypher);
        //double ic = Vigenere.calculateIC(cypher);
        //System.out.printf("Index of Coincidence: %.3f\n", ic);
        //System.out.println(b.Vdecrypt(cypher));
        //System.out.println(a.decrypt("nsjjimjquktwdtz" , 5));

    }


}
